### ISSUE TITLE
wasm-bindgen error has not being thrown properly

### ISSUE THREAD

**Issue by gabrielcarneiro97** [ashleygwilliams/wasm-pack#119] opened 2018-04-30 18:03 UTC
I've updated my wasm-bindgen-cli today and when I tried to use `wasm-pack init` it failed:

```
PS C:\Users\Gabriel\Projetos\Conways-Game-of-Life\rust-module> wasm-pack init
| [1/7] Adding WASM target...
| [2/7] Compiling to WASM...
| [3/7] Creating a pkg directory...
| [4/7] Writing a package.json...
| [5/7] Copying over your README...
| :-) [WARN]: origin crate has no README
| [6/7] Installing WASM-bindgen...
|  [INFO]: wasm-bindgen already installed
| [7/7] Running WASM-bindgen...
|  [ERR]: wasm-bindgen failed to execute properly
Details:

```
As you can see, the details of the wasm-bindgen error aren't being printed, so to discover what was happening I've to compile wasm-bindgen stand-alone. The solution that the wasm-bindgen offered worked, that was:

```
PS C:\Users\Gabriel\Projetos\Conways-Game-of-Life\rust-module> cargo build --target wasm32-unknown-unknown
   Compiling conways_game_of_life v0.1.2 (file:///C:/Users/Gabriel/Projetos/Conways-Game-of-Life/rust-module)
    Finished dev [unoptimized + debuginfo] target(s) in 5.57 secs
PS C:\Users\Gabriel\Projetos\Conways-Game-of-Life\rust-module> wasm-bindgen target/wasm32-unknown-unknown/debug/conways_game_of_life.wasm --out-dir .
error: failed to extract wasm-bindgen custom sections
        caused by:

it looks like the Rust project used to create this wasm file was linked against
a different version of wasm-bindgen than this binary:

  rust wasm file: 0.2.5
     this binary: 0.2.7

Currently the bindgen format is unstable enough that these two version must
exactly match, so it's required that these two version are kept in sync by
either updating the wasm-bindgen dependency or this binary. You should be able
to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen

or you can update the binary with

    cargo install -f wasm-bindgen-cli

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/alexcrichton/wasm-bindgen/issues!

```

I was wondering if this info should not appears at wasm-pack error details.

**Comment by mgattozzi** [comment] 2018-04-30 23:09
Hey @gabrielcarneiro97 this is a dupe of #117 actually! It should be printed out as an error but our assumption was that we only need to pull from stderr not just stdout. Would love to hear more of your thoughts and what you expect over in that issue!

**Closed by mgattozzi** 2018-04-30 23:09 UTC
